name: Build & Deploy to VPS

on:
  push:
    branches:
      - master

env:
  PROJECT_NAME: stacjownik

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Build the app
        run: yarn && yarn build
      - name: Setup SSH key for connection with the server
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Clear old assets
        run: ssh -o StrictHostKeyChecking=no -v -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} -p 2022 "rm -rf /var/www/$PROJECT_NAME/assets"
      - name: Send new files
        run: scp -o StrictHostKeyChecking=no -v -i ~/.ssh/id_rsa -P 2022 -r ./dist/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/$PROJECT_NAME